# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Install pyhton
      - name: setup python
        uses: actions/setup-python@v2
      - name : TEST
        run: |
          echo "$GITHUB_WORKSPACE"

        
      # Install drawbot
      - name: setup drawbot
        run: |
          sudo pip3 install git+https://github.com/typemytype/drawbot
          
      - name: setup fontmake
        run: |
          sudo pip3 install fontmake
          

      # Runs a set of commands using the runners shell
      - name: Init Folder
        run: |
          mkdir -p Instances Instances/Master Instances/Instance
          mkdir -p PDF PDF/KerningGroup PDF/FontDashboard PDF/Proofing
      #    rm Instances/Master/* Instances/Instance/* PDF/KerningGroup/* PDF/Proofing/*
          
      - name: Export Instances
        run: |
          cd "$GITHUB_WORKSPACE/Glyph File"
          for eachfile in *; do
            if [[ $eachfile =~ ".glyphs" ]]; then
              GLYPHFILE=$eachfile
              echo "$GLYPHFILE"
            fi
          done
          
          fontmake "$GLYPHFILE" -i --instance-dir {tmp} --master-dir {tmp} --output-dir "$GITHUB_WORKSPACE"/Instances/Instance
          fontmake "$GLYPHFILE" -o otf --instance-dir {tmp} --master-dir {tmp} --output-dir "$GITHUB_WORKSPACE"/Instances/Master
          echo PASS
      
      - name: Generate FontDashboard PDF
        run: |
          python Script/Font_Color_Dashboard_V2.py
          echo Script/Font_Color_Dashboard_V2
          
      - name: Generate Proofing PDF
        run: |
          python Script/ProofingPDF.py
          echo Script/ProofingPDF
          
      - name: Generate Kerning PDF
        run: |
          python Script/Show_Kerning_Groups.py
          echo Script/Show_Kerning_Groups PDF
                  
      #- name:  Commit File changes
      # skipping the commit code
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Auto] GitHub Action"
          commit_user_name: Hugo Jourdan
          commit_user_email: xhugo.jourdan@gmail.com
          commit_author: Hugo Jourdan <xhugo.jourdan@gmail.com>
      - name: Push changes                               
        uses: ad-m/github-push-action@master
        
        
